src/simple_statistics.js
test/perceptron.test.js

This adds `.perceptron()` for making a single-layer perceptron classifier with `.train()` and `.predict()` methods. Tests are in `perceptron.test.js`.
I haven't added anything to the README etc., but if this looks good that could also be done.

implement a simple perceptron classifier

---

package.json
src/median.js
src/median_sorted.js
src/quantile.js
src/quickselect.js
test/median.test.js
test/quickselect.test.js

A work in progress, closes #145. The first commit implements median using quickselect, making it much faster — from `O(N log N)` to `O(N)` for unsorted input.
For a sample benchmark on 1 million random numbers, the current implementation runs in 755ms. The new one is 28ms — 27 times faster.
Remaining tasks if the approach is approved:
cc @tmcw HAPPY BIRTHDAY!!! :cake: :cake: :cake:

Use quickselect to significantly speed up median and quantile

---

.flowconfig
package.json

Adds `.+/node_modules/config-chain/test/.+` to the flow ignored files and uses
jsdoctest@^1.6.1 with _"inter-requiring modules have trouble with the
first-require trick"_ (yamadapc/jsdoctest#26) fixed.

Use jsdoctest@^1.6.1 and fix the flow tests

---

index.js
src/sample.js
src/sample_with_replacement.js
src/shuffle.js
src/shuffle_in_place.js
test/sample_with_replacement.test.js

Implements simple sampling with replacement, which, in contrast to the existing sample method,
allows an item to be chosen more than once.
Fixes https://github.com/simple-statistics/simple-statistics/issues/173

feat(core): sampleWithReplacement

---

.flowconfig

A file from the `conventional-changelog-core` package was breaking `flow check`.

Fixing build

---

test/add_to_mean.js

Just dropping an irrelevant test assertion in the `addToMean` tests. I probably copy-pasted it from the `mean` tests and forgot to drop it earlier.

Dropping irrelevant test for addToMean

---

code_of_conduct.md

This is the same as I use in documentation.js, and will apply to all future contributions. The
contributors convenant is very simple, liberal, and well-known.

docs(coc): Add Contributor's Covenant as CoC

---

src/sum.js

Hello `simple-statistics`.
I tried some things to improve the performance of the `sum` function without compromising the float rounding error correction and stumbled upon the Kahan-Babuska algorithm (you can read a description of the algorithm in [this](https://pdfs.semanticscholar.org/1760/7d467cda1d0277ad272deb2113533131dc09.pdf) paper).
It's faster because it can apply the correction at the end rather than at each iteration.
What do you think?

Implementing the Kahan-Babuska algorithm

---

src/poisson_distribution.js

Improves performance of `poissonDistribution` by computing factorial cumulatively. Ref #194
Improves time from 766ms to 218ms for the following simple benchmark:
```js
for (var i = 1; i < 50000; i++) poissonDistribution(i % 1000);
```
@tmcw after this PR and #205, `factorial.js` is no longer needed, and since it's not directly a statistical function, should we just remove it from `simple-statistics`?

Faster poissonDistribution

---

src/poisson_distribution.js

A further ~5% poissonDistribution performance improvement.

Use Math.exp instead of Math.pow

---

src/binomial_distribution.js

Improves performance of `binomialDistribution` by computing binomial coefficient cumulatively instead of using factorials in each iteration. Ref #194
Improves time from 3.8s to 450ms for the following simple benchmark:
```js
for (var i = 1; i < 50000; i++) binomialDistribution(i, Math.random());
```

Faster binomialDistribution

---

src/bernoulli_distribution.js
src/binomial_distribution.js
src/poisson_distribution.js
test/bernoulli_distribution.test.js

Makes `bernoulliDistribution`, `binomialDistribution` and `poissonDistribution` return an array instead of object. The result is fully requivalent since keys were sequential integers starting from 0, but this is ~5% faster.

Return array instead of object in distribution functions

---

index.js
src/sample_kurtosis.js
test/sample_kurtosis.test.js

Uses Fisher’s excess kurtosis definition with unbiased central moment
estimators (used in Excel and SAS, also SciPy’s stats.kurtosis when
bias=False). Pretty similar to sampleSkewness.
Fixes #218

Adds sampleKurtosis

---

README.md

This also removes the bower installation method, because it was dropped by unpkg. This documentation
now shows how to install and use simple-statistics, and is super, super explicit about how to use
it, I hope.
Fixes #227

docs: Very detailed installation directions

---

package.json

standard-version also updates the changelog, so this command and dependency were dead code.

build: Remove standard-changelog dependency

---

README.md

Fixes #263 - adds documentation for the type=module trick.

Document import module strategy

---

index.js
src/permutation_test.js
test/permutation_test.test.js

Hello everyone -
Here's an implementation of `permutation_test` (see issue #271 ); hopefully the first of many statistical tests to be added :)
I opted for the `alternative` argument as opposed to `null` because that's congruent with the APIs for similar `R` functions (e.g. `coin::independence_test`, `t.test`, `wilcox.test`), so I figured I'd keep it.

new feature: permutation test

---

package.json

This makes tests about 2x faster on my computer, but no big change on CircleCI, which I think is fine - there's no notable decrease of performance on Circle either.

Try using --jobs=4 to make tap test runs faster

---

src/gamma.js

* Number.isInteger is not supported in IE11: https://caniuse.com/#search=isinteger
* Polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger
Refs #296

fix: Polyfill Number.isInteger function before committing to dropping IE11

---

package.json

unpkg.com, a NPM CDN, uses an unpkg field, then the browser field (undocumented), and then the main field to find a package's entry point. By adding the unpkg field, simple-statistics will only rely on unpkg's documented behavior.
References d3-require: https://github.com/d3/d3-require/issues/12

build(package): Add unpkg field to package.json

---

README.md

In HTML5, `<script>` is not a [void element](https://www.w3.org/TR/html5/syntax.html#void-elements) and therefore needs to be closed, otherwise it "eats" whatever comes after it (until `</script>` is encountered).
This might not apply to [XML-serialized HTML5](https://mathiasbynens.be/notes/xhtml5), but I don't know anyone who uses that.
Note that even for void elements, trailing slashes are [not recommended](http://codeguide.co/#html-syntax). Presumably because they are optional, and because they [lead people to believe](https://xkcd.com/386/) that normal elements can also be self-closed.
See also: Angular[JS] https://github.com/angular/angular.js/issues/1953 / https://github.com/angular/angular/issues/5563
The closing tag is on a new line, because otherwise GitHub adds an ugly …

docs(readme): Close script tag

---

src/quantile_rank.js

There is a typo in the quantileRank description that seems to change the intent of the text, suggesting users should presort their input data. I believe the intended meaning was to point out that quantileRank will sort automatically for a performance penalty, which is what the source appears to do.

better quantileRank description

---

index.d.ts
src/extent.d.ts

It appears the typings for extent are not currently being exported ( extent itself is), this adds the types file for extent, and adds it to the index.d.ts exports

add missing typings for extent

---

README.md
package.json

Node 13 includes another way to include modules. This is terrible, the only way to explain a modern package.json is with excuses.

build: Node v13 import support

---

index.js
src/mean_simple.d.ts
src/mean_simple.js
test/mean_simple.test.js

Internally, the standard `mean` function is using a `sum` function which goes beyond successive addition to correct for floating-point errors. The benchmarked `mean` function in the jStat library does not provide this, so the benchmark is not testing against which code is more performant, but instead testing two different algorithms.
Since the `sumSimple` function is already provided, it follows on that `meanSimple` can be used to provide an end user with an option for a more performant mean, at the cost of precision. This also allows the benchmark against jStat to be far closer, and in my tests actually outperforming.

Simple mean

---

.github/workflows/nodejs.yml
README.md

We lost coverage reporting a while back - I'm not sure when, maybe I just forgot to port it in the switch to GitHub Actions. This tries to put it back.

test: Update Coveralls coverage reporting

---

src/permutation_test.d.ts
src/permutation_test.js
test/permutation_test.test.js

Our tests were nondeterministic: testing permutationTest used Math.random indirectly, via shuffleInPlace. This adds a randomSource argument to permutationTest so it can be tested consistently.

feat: Add randomSource argument to permutationTest

---

README.md

This change to the readme makes it clearer that skypack is a good option to use simple-statistics with Deno. Refs #456

docs: Suggest deno usage option.

---

src/sample_covariance.js

This reference is either outdated or never worked in the first place.

Fix "Sample mean and covariance" reference

---

src/shuffle.js

The previous implementation of shuffle created two shallow copies, one of which was unnecessary.

Avoid unnecessary copy in shuffle

---

src/mode.js
src/mode_fast.js
src/mode_sorted.js

From what I can tell, the redirect was used because the URL contains parentheses, which break markdown. This patch changes the third-party redirect to a direct URL with percent-encoded parentheses in accordance with the markdown and URI rules.
By the way, thanks for this project @tmcw!

Link directly to Wikipedia instead of redirect

---

CONTRIBUTING.md
src/extent.js
src/geometric_mean.js
src/harmonic_mean.js
src/max.js
src/mean.js
src/mean_simple.js
src/min.js
src/mode.js
src/product.js
src/root_mean_square.js
src/sum.js
src/sum_simple.js

I believe that this is more readable and closer to being grammatically correct.

Improve use of Big-O notation in src/docs

---

src/ckmeans.js

Fixes #520.
I don't know what I'm doing, but this way around it's closer to what the [reference implementation does](https://github.com/rocketrip/ckmeans/blob/49eb1bb9ca5467fdc153fe5d20f027ab7375c078/Ckmeans.1d.dp/src/Ckmeans.1d.dp.cpp#L102), and the tests still pass 🙃 
And it's way faster: Results using @breck7's test code from https://github.com/simple-statistics/simple-statistics/issues/520#issuecomment-719809868:
Before (without this fix):
```
kSize,nSize,time
5,1000,22
5,2000,33
5,10000,180
5,20000,820
5,100000,37749
5,200000,201173
```
After (with this fix):
```
kSize,nSize,time
5,1000,15
5,2000,29
5,10000,32
5,20000,52
5,100000,125
5,200000,324
```
cc @schnerd for review if you find the time, and this may be something you want to fix in your own ckmeans packages, too.

fix: increase `ckmeans` performance

---

index.d.ts
src/silhouette.d.ts

I found that the `silhouette` function was missing TypeScript bindings and could not be imported without them.  The goal of this PR is to add the necessary bindings for this function.

Add TypeScript bindings for silhouette.

---

test/binomial_distribution.test.js
test/coefficient_of_variation.test.js
test/combinations.test.js
test/k_means_cluster.test.js
test/linear_regression.test.js
test/mad.test.js
test/permutation_test.test.js
test/r_squared.test.js
test/sample_covariance.test.js
test/sample_kurtosis.test.js
yarn.lock

This bumps prettier in `yarn.lock` and fixes the resulting lint errors. (I noticed there was a PR from dependabot only bumping the version; not totally sure how dependabot works but I think this PR can supersede that one.)
With this change cloning locally and then simply doing
```
npm install
npm run test
```
should result in clean output.

Bump prettier and fix lint errors

---

index.js
src/sample_rank_correlation.d.ts
src/sample_rank_correlation.js
test/sample_correlation.test.js

@dsaxton for your consideration, decided to take a shot at seeing whether we could support duplicate indexes in this algorithm. This does, by first recording the indexes before sorting.
The benefits are that this supports duplicate values and also improves performance (in big-o terms) because it removes the `indexOf`, which was in the worst case was n².
On the downside, it's a bit more code, and it will use a little more memory, in the form of temporary arrays.

Rank correlation

---

src/t_test_two_sample.js

Closes https://github.com/simple-statistics/simple-statistics/issues/519
This replaces the existing link with a live one, and makes a small tweak to the wording (philosophical point, but we might want to avoid implying we accept a null whenever we don't reject it).

docs: Modify t-test doc text and link

---

package.json
test/types.ts

@tmcw I noticed `prettier` was only being run against TypeScript declaration files, so I thought it might be helpful to expand it to most of the code base (here including all of `src` and `test` other than the autogenerated `test/types.js` file)

build: Expand prettier linting

---

index.js
src/wilcoxon_rank_sum..d.ts
src/wilcoxon_rank_sum.js
test/wilcoxon_rank_sum.test.js

@tmcw I'm not sure if this is something you'd be interested in adding, but this PR implements a calculation of the Wilcoxon rank sum statistic, which is a popular non-parametric alternative to the two sample t-test. The code gets a tad messy, primarily because we need to make sure that ranks of tied values get replaced by the average rank within the group (else the statistic isn't well-defined). Please let me know if you think there's a more elegant way to do this.
Also worth pointing out that this _only_ calculates the value of the test statistic, and doesn't provide any utilities for performing inference on that value.

feat: Implement Wilcoxon rank sum statistic

---

index.d.ts
src/silhouette_metric.d.ts

The typings were `silhouette` were also forgot in the original implementation (https://github.com/simple-statistics/simple-statistics/pull/485) but that was fixed here: https://github.com/simple-statistics/simple-statistics/pull/549

Add missing TypeScript typing for `silhouetteMetric`

---

package.json

Via [Socket](https://socket.dev/npm/package/simple-statistics), I've realized that the LICENSE file for this module isn't included in the npm module. This will include it.
No change to the licensing, just making sure that the file is included.

build: Include LICENSE file in NPM package

---

package.json

Quick fix, the export map needs a `types` field with nodenext resolution and doesn't use the root `types` field

Support TypeScript nodenext module resolution

---

package.json

- Fixes #527
Via publint's checking https://publint.dev/simple-statistics@7.8.1
Oddly typescript requires the `types` member to be first in the `exports` object. Odd!

build: Add browser to exports in package.json. Move TS to the top.

---

package.json

7.8.4 updated the allowed versions of Node for installing simple-statistics, but as a dependency-free module, this shouldn't really be required. Fixes #730.

build: Allow any version of Node

---

mise.toml
package.json

I've switched all my local-tools version management to `mise`, so switching this project as well. It's great.

build: Switch from volta to mise
