- README.md
- docs/docco.css
- docs/simple_statistics.html
- src/simple_statistics.js
- test/cumulative.js
- test/error_function.js
And add a numerical approximation to error_function() instead of only having a table lookup.
> Fix rounding error in cumulative_std_normal_probability lookup.

- src/simple_statistics.js
- test/jenks.test.js
A fix for https://github.com/tmcw/simple-statistics/issues/88
> Fix for jenksBreaks() to correctly pull the breaks values

- README.md
Add wiki link for Median Absolute Deviation (MAD)
> Add wiki link for MAD

- .eslintrc
- src/simple_statistics.js
- test/amd.test.js
/cc @NerdYouDontKnow @stevemandl  mind trying out this branch and confirming that it'll fix #93
> Use larger umd declaration to be valid even in the case of use strict

- .gitignore
- API.md
- Makefile
- README.md
- docs/simple_statistics.html
- src/simple_statistics.js
This syncs the automatically generated documentation with the current version of source (after minor tweaks for readability, etc.) and adds `perceptron` documentation to README.md (and API.md).
Also I noticed that the `make test` was talking about mocha, which didn't seem to make sense, so I took that out.
> update/sync docs/add perceptron to README

- src/harmonic_mean.js
Use full sentences so that generated documented is more readable.
> Update function comment

- src/equal_interval_breaks.js
- test/equal_interval_breaks.test.js
cc @morganherlocker could you do a quick code review?
> Implement equalIntervalBreaks. Fixes #57

- .eslintrc
- index.js
- src/median_sorted.js
- src/mode.js
- src/mode_sorted.js
- test/median.test.js
- test/mode.test.js
> Sorted methods

- index.js
- src/bisect.js
- src/sign.js
- test/bisect.test.js
- test/sign.test.js
find root of a function with the bisection method
https://en.wikipedia.org/wiki/Bisection_method
> Implement bisect

- CHANGELOG.md
- index.js
- src/permutations_heap.js
- test/permutations_heap.js
> Implement permutations. Fixes #154

- src/bayesian_classifier.js
minor clean up and remove unnecessary conditional statement
> minor clean up bayesian_classifier

- src/chunk.js
previous example is little ambiguous
> update chunk example to make it more clear

- index.js
- scripts/required_test.js
- src/combinations.js
- test/combinations.test.js
Saw there was a permutations algorithm, but nothing that supported combinations. Never written flow before, but I think I got this gist?
I'd be happy to write some more combinatorics algs if you guys are interested!
> Adds support for n-choose-k type permutations, no replacement

- test/quickselect.test.js
This uses specially-crafted input to hit line 35's
else condition
> Improve coverage of quickselect algorithm

- src/max.js
- src/min.js
Something small that I noticed.
> Fix comment: value is undefined, not NaN

- .flowconfig
- package.json
Fixes https://github.com/simple-statistics/simple-statistics/issues/175
> chore(deps): Upgrade dependencies

- .flowconfig
- index.js
- src/mode_fast.js
- test/mode.test.js
Test for #177
I have some hacky benchmarks to push as well, which I should. It looks like modeFast is reliably faster than mode, but around 30%
> Implement indexed mode

- .flowconfig
- index.js
- src/add_to_mean.js
- test/add_to_mean.js
Adding a function taking the current mean, the number of elements in the list and a value to add and returning the new mean in constant time.
Will add more functions of the kind when I am confident I contributed the correct way.
> Add to mean

- index.js
- src/subtract_from_mean.js
- test/subtract_from_mean.js
After `addToMean`, `subtractFromMean`. :)
> Adding subtractFromMean

- index.js
- src/combine_means.js
- test/combine_means.js
Adding the `combineMeans` function that take two means and the length of the lists that they are from and return the combined mean in constant time.
> Adding combineMeans

- SEEALSO.md
Also mention Python3's statistics module
Fixes #190
> docs(seealso): descriptive_statistics is a Ruby gem

- src/bernoulli_distribution.js
No need to implement through binomial distribution since the result is trivial.
> Simpler bernoulliDistribution

- src/sample_skewness.js
Edited to reflect error throwing when input array has length <3.
> Fixes JSDoc in sampleSkewness

- src/add_to_mean.js
- src/combine_means.js
- src/combine_variances.js
- src/sample_skewness.js
- src/subtract_from_mean.js
This JSDoc tag makes it clear in documentation which version includes a certain feature
> docs: Add `@since` information to new methods

- benchmarks/index.js
- benchmarks/package.json
* upgrading ssMaster version
* differentiating between `variance` & `sampleVariance` in the benchmark
> chore(benchmark): benchmark upgrade

- package.json
Ref: https://github.com/simple-statistics/simple-statistics/issues/253
> Add index.js to package.json

- index.js
- src/extent.js
- src/extent_sorted.js
- test/minmax.test.js
Adding the `extent` function. Related to #280.
> feat: adding extent

- package.json
> chore(package): update flow-bin to version 0.70.0

- index.js
- src/gamma.js
- test/gamma.test.js
Here's an implementation of the [Gamma Function](https://en.wikipedia.org/wiki/Gamma_function), which is just a continuous approximation to factorial.
I wrote this because I wanted to implement some other methods that require particular distributions, that themselves require the gamma function.
I think most implementations use the Stirling approximation, but I found a paper that claims to have a superior implementation [(Nemes approximation)](https://arxiv.org/abs/1003.6020), so I just used that bad boy.
For negative inputs, I used [Euler's reflection formula](https://en.wikipedia.org/wiki/Gamma_function#Properties) , which I found via [Gyu Eun Lee's answer on math.stachexchange](https://math.stackexchange.com/questions/396889/how-to-find-the-factorial-of-a-fraction).
The results yield …
> Gamma Function

- package.json
> chore(package): update tap to version 12.0.1

- package.json
> chore(package): update documentation to version 7.1.0

- src/permutation_test.d.ts
Fixes #298 
cc @benoneal @jwilber mind taking a look? I'm not a big TypeScript user so am kind of just trying to imitate existing definitions.
> fix(permutationTest): Add TypeScript definition for permutationTest

- src/quantile.js
- test/quantile.test.js
> Fix array quantile on certain kinds of input

- package.json
> chore(package): update microbundle to version 0.8.1

- package.json
> chore(package): update documentation to version 9.1.1

- SEEALSO.md
Hi I added my library to your list ot math libs
> Hi I added my library to your list ot math libs

- src/geometric_mean.js
- src/harmonic_mean.js
- src/max.js
- src/mean.js
- src/mean_simple.js
- src/median_absolute_deviation.js
- src/min.js
- src/sample_standard_deviation.js
- src/sample_variance.js
- src/variance.js
These comments were added in much earlier versions of this software, and do not describe the current version correctly. In these places, the new version seems to be mostly self-explanatory, so I removed the comments instead of updating them.
> Remove incorrect/outdated comments from source

- README.md
- index.js
- src/coefficient_of_variation.d.ts
- src/coefficient_of_variation.js
- test/coefficient_of_variation.test.js
Version of #528 with a few final polish changes:
- Cleaned up code style to pass prettier & eslint rules
- Adds test case
- Exports new method from main.
> Angelyaaaaa master

- src/t_test.js
Just a tiny typo in the documentation :)
> Fix capitalization in t_test.js

- package.json
> Update exports section of package.json.

- src/standard_normal_table.js
Closes https://github.com/simple-statistics/simple-statistics/issues/395
I think I agree with the original post that this is a little confusing. Maybe just removing the last sentence and moving the link into the paragraph above would help? What do you think @tmcw?
> docs: Update normal CDF doc

- README.md
- package.json
- src/sum.js
- src/sum_simple.js
- test/sum.test.js
- yarn.lock
> fix: Return NaN on sum with non-number inputs

- index.d.ts
- index.js
- jenks_matrices.js
- package.json
- src/jenks.d.ts
- src/jenks.js
- src/jenks_breaks.js
- src/jenks_matrices.js
- test/jenks.test.js
- test/types.ts
Polish branch for #673    
- Update tests for new tap (replaces deepEqual with same)
- Add TypeScript definition
> Bring back jenks

- index.d.ts
> fix: Export sampleRankCorrelation type

- src/cumulative_std_normal_probability.js
> Faster rounding in `cumulativeStdNormalProbability`
